nodes:
  pi:
    docker_containers:
      - container_name: frr
        image: quay.io/frrouting/frr:10.3.0
        cap_add:
          - net_admin
          - sys_admin
        hostname: pi
        volumes:
          - type: bind
            source: "./nodes/pi/frr/config/daemons"
            target: "/etc/frr/daemons"
        autoremove: true
    controlplane:
      container_name: frr
      ospf:
        - vrf: default
          router_id: "10.3.64.1"
          interfaces:
            - name: v5-dummy
              area: "0.0.0.0"
              passive: true
            - name: veth1
              area: "0.0.0.0"
              network: point-to-point
      bgp:
        - vrf: default
          asn: 65001
          router_id: "10.3.64.1"
          no_ipv4_unicast: true
          address_families:
            - afi: l2vpn
              safi: evpn
              advertise_all_vni: true
              advertise_svi_ip: true
          # neighbors is a map of map[group][]PeerConfig
          neighbors:
            group1:
              asn: 65001
              capabilities:
                - extended-nexthop
              peers:
                - address: "10.3.82.66"
                - address: "10.3.98.66"

    dataplane:
      openvpn:
        - name: pi
          client: true
          dev: tap0
          proto: tcp
          remote:
            host: "148.135.56.215"
            port: 21194
          resolv_retry: infinite
          nobind: true
          http_proxy:
            host: "ss"
            port: 8080
          cert_file: /etc/openvpn/certs/client-cert.pem
          key_file: /etc/openvpn/certs/client-key.pem
          peer_fingerprint: "A6:79:F7:4A:0C:A6:4A:D1:6F:85:2E:25:8F:D8:C2:2A:62:4F:61:FB:4C:5C:38:11:5E:4E:39:51:93:11:DD:DF"
          remote_cert_tls: server
          verb: 3
          keepalive:
            interval_secs: 30
            patience_secs: 120
          up_cmd: /up-wrapper.sh
          script_security_level: 3
          executable_path: "openvpn"
          docker_container:
            networks:
              - ss
            autoremove: true
            image: openvpn:latest
            container_name: "openvpn-connector-1"
            cap_add:
              - net_admin
              - sys_admin
            hostname: pi
            ports:
              "1194/tcp":
                - host_ip: "0.0.0.0"
                  host_port: 21194
                - host_ip: "::"
                  host_port: 21194
            volumes:
              - type: bind
                source: "./nodes/pi/openvpn/up-wrapper.sh"
                target: "/up-wrapper.sh"
              - type: bind
                source: "./nodes/pi/openvpn/certs/client-cert.pem"
                target: "/etc/openvpn/certs/client-cert.pem"
              - type: bind
                source: "./nodes/pi/openvpn/certs/client-key.pem"
                target: "/etc/openvpn/certs/client-key.pem"
            devices:
              - path_on_host: "/dev/net/tun"
                path_in_container: "/dev/net/tun"
                cgroup_permissions: "rwm"
    virtual_interface:
      dummy:
        - name: dummy0
          cidr: "10.3.64.1/24"
  lax1:
    controlplane:
      container_name: frr
      ospf:
        - vrf: default
          router_id: 10.3.64.1
          interfaces:
            - name: v5-dummy
              area: 0.0.0.0
              passive: true
            - name: veth1
              area: 0.0.0.0
              network: point-to-point
      bgp:
        - vrf: default
          router_id: 10.3.64.1
    dataplane:
      openvpn:
        - name: tap0
          dh_cert_file: /path/to/dh2048.pem
          cert_file: /path/to/cert.pem
          cert_key_file: /path/to/key.pem
          pin_sha256: "06:00:DD:D5:77:82:A0:E6:E5:5F:C4:A0:F5:D3:5A:98:23:6E:E5:DC:86:D3:AB:60:9F:01:1B:97:D4:A6:60:BE"
          tuntap: tap
          container:
            docker:
              name: openvpn-server
          role: server
      wireguard:
        - name: wg-lax1-mnz1
          privatekey: yAnz5TF+lXXJte14tji3zlMNq+hd2rYUIgJBgB3fBmk=
          peers:
            - publickey: xTIBA5rboUvnH4htodjb6e697QjLERt1NAB4mZqp8Dg=
              endpoint: 192.95.5.67:1234
              allowedips:
                - "0.0.0.0/0"
                - "::/0"
          addresses:
            - peer: "10.192.122.3/32"
              local: "10.192.122.3"
          mtu: 1420
          container_name: frr
      vxlan:
        - vxlan_id: 42
          local_ip: "10.3.64.1"
          mtu: 1370
          name: vx42
          nolearning: true
          container_name: frr
      veth:
        - name: veth1
          container_name: openvpn-connector-1
          peer:
            name: veth1
            container_name: frr
      bridge:
        - name: br0
          slave_interfaces:
            - name: veth1
          container_name: frr
        - name: br0
          slave_interfaces:
            - name: tap0
            - name: veth1
          container_name: openvpn-connector-1
    virtual_interface:
      dummy:
        - name: v5-dummy
          cidr: "10.3.64.1/24"
          container_name: frr
