//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package bird

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in BGPCapabilitiesInfo) DeepCopyInto(out *BGPCapabilitiesInfo) {
	{
		in := &in
		*out = make(BGPCapabilitiesInfo, len(*in))
		copy(*out, *in)
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPCapabilitiesInfo.
func (in BGPCapabilitiesInfo) DeepCopy() BGPCapabilitiesInfo {
	if in == nil {
		return nil
	}
	out := new(BGPCapabilitiesInfo)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPProtoBasics) DeepCopyInto(out *BGPProtoBasics) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPProtoBasics.
func (in *BGPProtoBasics) DeepCopy() *BGPProtoBasics {
	if in == nil {
		return nil
	}
	out := new(BGPProtoBasics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPProtoInfo) DeepCopyInto(out *BGPProtoInfo) {
	*out = *in
	if in.Basics != nil {
		in, out := &in.Basics, &out.Basics
		*out = new(BGPProtoBasics)
		**out = **in
	}
	if in.VRF != nil {
		in, out := &in.VRF, &out.VRF
		*out = new(string)
		**out = **in
	}
	if in.BGPState != nil {
		in, out := &in.BGPState, &out.BGPState
		*out = new(string)
		**out = **in
	}
	if in.NeighborAddress != nil {
		in, out := &in.NeighborAddress, &out.NeighborAddress
		*out = new(string)
		**out = **in
	}
	if in.NeighborAS != nil {
		in, out := &in.NeighborAS, &out.NeighborAS
		*out = new(string)
		**out = **in
	}
	if in.LocalAS != nil {
		in, out := &in.LocalAS, &out.LocalAS
		*out = new(string)
		**out = **in
	}
	if in.NeighborID != nil {
		in, out := &in.NeighborID, &out.NeighborID
		*out = new(string)
		**out = **in
	}
	if in.Session != nil {
		in, out := &in.Session, &out.Session
		*out = new(string)
		**out = **in
	}
	if in.SourceAddress != nil {
		in, out := &in.SourceAddress, &out.SourceAddress
		*out = new(string)
		**out = **in
	}
	if in.HoldTimer != nil {
		in, out := &in.HoldTimer, &out.HoldTimer
		*out = new(string)
		**out = **in
	}
	if in.KeepaliveTimer != nil {
		in, out := &in.KeepaliveTimer, &out.KeepaliveTimer
		*out = new(string)
		**out = **in
	}
	if in.SendHoldTimer != nil {
		in, out := &in.SendHoldTimer, &out.SendHoldTimer
		*out = new(string)
		**out = **in
	}
	if in.LocalCapabilities != nil {
		in, out := &in.LocalCapabilities, &out.LocalCapabilities
		*out = make(BGPCapabilitiesInfo, len(*in))
		copy(*out, *in)
	}
	if in.NeighborCapabilities != nil {
		in, out := &in.NeighborCapabilities, &out.NeighborCapabilities
		*out = make(BGPCapabilitiesInfo, len(*in))
		copy(*out, *in)
	}
	if in.Channels != nil {
		in, out := &in.Channels, &out.Channels
		*out = make(map[string]ChannelInfo, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPProtoInfo.
func (in *BGPProtoInfo) DeepCopy() *BGPProtoInfo {
	if in == nil {
		return nil
	}
	out := new(BGPProtoInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPProtocol) DeepCopyInto(out *BGPProtocol) {
	*out = *in
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(string)
		**out = **in
	}
	if in.Interface != nil {
		in, out := &in.Interface, &out.Interface
		*out = new(string)
		**out = **in
	}
	if in.LocalAddress != nil {
		in, out := &in.LocalAddress, &out.LocalAddress
		*out = new(string)
		**out = **in
	}
	if in.PeerAddress != nil {
		in, out := &in.PeerAddress, &out.PeerAddress
		*out = new(string)
		**out = **in
	}
	if in.LocalASN != nil {
		in, out := &in.LocalASN, &out.LocalASN
		*out = new(string)
		**out = **in
	}
	if in.PeerASN != nil {
		in, out := &in.PeerASN, &out.PeerASN
		*out = new(string)
		**out = **in
	}
	if in.PeerExternal != nil {
		in, out := &in.PeerExternal, &out.PeerExternal
		*out = new(bool)
		**out = **in
	}
	if in.PeerInternal != nil {
		in, out := &in.PeerInternal, &out.PeerInternal
		*out = new(bool)
		**out = **in
	}
	if in.Node != nil {
		in, out := &in.Node, &out.Node
		*out = new(string)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPProtocol.
func (in *BGPProtocol) DeepCopy() *BGPProtocol {
	if in == nil {
		return nil
	}
	out := new(BGPProtocol)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BirdBGPProtocolStatus) DeepCopyInto(out *BirdBGPProtocolStatus) {
	*out = *in
	if in.CurrentConfig != nil {
		in, out := &in.CurrentConfig, &out.CurrentConfig
		*out = new(BGPProtocol)
		(*in).DeepCopyInto(*out)
	}
	if in.ProtocolStatus != nil {
		in, out := &in.ProtocolStatus, &out.ProtocolStatus
		*out = new(BGPProtoInfo)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BirdBGPProtocolStatus.
func (in *BirdBGPProtocolStatus) DeepCopy() *BirdBGPProtocolStatus {
	if in == nil {
		return nil
	}
	out := new(BirdBGPProtocolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChannelInfo) DeepCopyInto(out *ChannelInfo) {
	*out = *in
	if in.Preference != nil {
		in, out := &in.Preference, &out.Preference
		*out = new(int)
		**out = **in
	}
	if in.RoutesStat != nil {
		in, out := &in.RoutesStat, &out.RoutesStat
		*out = new(ChannelRoutesStat)
		**out = **in
	}
	if in.RouteChangesStat != nil {
		in, out := &in.RouteChangesStat, &out.RouteChangesStat
		*out = new(ChannelRouteChangesStat)
		(*in).DeepCopyInto(*out)
	}
	if in.BGPNextHop != nil {
		in, out := &in.BGPNextHop, &out.BGPNextHop
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChannelInfo.
func (in *ChannelInfo) DeepCopy() *ChannelInfo {
	if in == nil {
		return nil
	}
	out := new(ChannelInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChannelRouteChangesStat) DeepCopyInto(out *ChannelRouteChangesStat) {
	*out = *in
	if in.ImportUpdates != nil {
		in, out := &in.ImportUpdates, &out.ImportUpdates
		*out = new(ChannelRouteChangesStatEntry)
		(*in).DeepCopyInto(*out)
	}
	if in.ImportWithdraws != nil {
		in, out := &in.ImportWithdraws, &out.ImportWithdraws
		*out = new(ChannelRouteChangesStatEntry)
		(*in).DeepCopyInto(*out)
	}
	if in.ExportUpdates != nil {
		in, out := &in.ExportUpdates, &out.ExportUpdates
		*out = new(ChannelRouteChangesStatEntry)
		(*in).DeepCopyInto(*out)
	}
	if in.ExportWithdraws != nil {
		in, out := &in.ExportWithdraws, &out.ExportWithdraws
		*out = new(ChannelRouteChangesStatEntry)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChannelRouteChangesStat.
func (in *ChannelRouteChangesStat) DeepCopy() *ChannelRouteChangesStat {
	if in == nil {
		return nil
	}
	out := new(ChannelRouteChangesStat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChannelRouteChangesStatEntry) DeepCopyInto(out *ChannelRouteChangesStatEntry) {
	*out = *in
	if in.Received != nil {
		in, out := &in.Received, &out.Received
		*out = new(int)
		**out = **in
	}
	if in.Rejected != nil {
		in, out := &in.Rejected, &out.Rejected
		*out = new(int)
		**out = **in
	}
	if in.Filtered != nil {
		in, out := &in.Filtered, &out.Filtered
		*out = new(int)
		**out = **in
	}
	if in.Ignored != nil {
		in, out := &in.Ignored, &out.Ignored
		*out = new(int)
		**out = **in
	}
	if in.Accepted != nil {
		in, out := &in.Accepted, &out.Accepted
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChannelRouteChangesStatEntry.
func (in *ChannelRouteChangesStatEntry) DeepCopy() *ChannelRouteChangesStatEntry {
	if in == nil {
		return nil
	}
	out := new(ChannelRouteChangesStatEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChannelRoutesStat) DeepCopyInto(out *ChannelRoutesStat) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChannelRoutesStat.
func (in *ChannelRoutesStat) DeepCopy() *ChannelRoutesStat {
	if in == nil {
		return nil
	}
	out := new(ChannelRoutesStat)
	in.DeepCopyInto(out)
	return out
}
