//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package wireguard

import (
	common "github.com/internetworklab/netapply/pkg/interface/common"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardInterfaceStatus) DeepCopyInto(out *WireGuardInterfaceStatus) {
	*out = *in
	if in.InterfaceStatus != nil {
		in, out := &in.InterfaceStatus, &out.InterfaceStatus
		*out = new(common.CommonInterfaceStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = make([]WireGuardPeerStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardInterfaceStatus.
func (in *WireGuardInterfaceStatus) DeepCopy() *WireGuardInterfaceStatus {
	if in == nil {
		return nil
	}
	out := new(WireGuardInterfaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardPeerStatus) DeepCopyInto(out *WireGuardPeerStatus) {
	*out = *in
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(string)
		**out = **in
	}
	if in.AllowedIPs != nil {
		in, out := &in.AllowedIPs, &out.AllowedIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PersistentKeepalive != nil {
		in, out := &in.PersistentKeepalive, &out.PersistentKeepalive
		*out = new(int)
		**out = **in
	}
	if in.PresharedKey != nil {
		in, out := &in.PresharedKey, &out.PresharedKey
		*out = new(string)
		**out = **in
	}
	if in.LastHandshakeAt != nil {
		in, out := &in.LastHandshakeAt, &out.LastHandshakeAt
		*out = new(int64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardPeerStatus.
func (in *WireGuardPeerStatus) DeepCopy() *WireGuardPeerStatus {
	if in == nil {
		return nil
	}
	out := new(WireGuardPeerStatus)
	in.DeepCopyInto(out)
	return out
}
