//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package common

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddressConfig) DeepCopyInto(out *AddressConfig) {
	*out = *in
	if in.Peer != nil {
		in, out := &in.Peer, &out.Peer
		*out = new(string)
		**out = **in
	}
	if in.Local != nil {
		in, out := &in.Local, &out.Local
		*out = new(string)
		**out = **in
	}
	if in.CIDR != nil {
		in, out := &in.CIDR, &out.CIDR
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddressConfig.
func (in *AddressConfig) DeepCopy() *AddressConfig {
	if in == nil {
		return nil
	}
	out := new(AddressConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonInterfaceStatus) DeepCopyInto(out *CommonInterfaceStatus) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonInterfaceStatus.
func (in *CommonInterfaceStatus) DeepCopy() *CommonInterfaceStatus {
	if in == nil {
		return nil
	}
	out := new(CommonInterfaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerInfo) DeepCopyInto(out *ContainerInfo) {
	*out = *in
	if in.Docker != nil {
		in, out := &in.Docker, &out.Docker
		*out = new(string)
		**out = **in
	}
	if in.Podman != nil {
		in, out := &in.Podman, &out.Podman
		*out = new(string)
		**out = **in
	}
	if in.NetnsPath != nil {
		in, out := &in.NetnsPath, &out.NetnsPath
		*out = new(string)
		**out = **in
	}
	if in.HostNetns != nil {
		in, out := &in.HostNetns, &out.HostNetns
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerInfo.
func (in *ContainerInfo) DeepCopy() *ContainerInfo {
	if in == nil {
		return nil
	}
	out := new(ContainerInfo)
	in.DeepCopyInto(out)
	return out
}
