//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package common

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonInterfaceStatus) DeepCopyInto(out *CommonInterfaceStatus) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonInterfaceStatus.
func (in *CommonInterfaceStatus) DeepCopy() *CommonInterfaceStatus {
	if in == nil {
		return nil
	}
	out := new(CommonInterfaceStatus)
	in.DeepCopyInto(out)
	return out
}
