volumes:
  mongodb-data:
    external: true
  mongodb-log:
    external: true
  mongodb-config:
    external: true
services:
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"
      - "[::1]:27017:27017"
    volumes:
      - "mongodb-data:/data/db"
      - "mongodb-log:/var/log/mongodb"
      - "mongodb-config:/data/configdb"
    restart: unless-stopped
